import { stringify as stringifyYaml } from "yaml";
import type { CiConfig, GeneratedFile, WorkflowConfig } from "./types.js";

const GENERATED = "# Generated by @mythral0/workflow-bootstrap. Edit .workflow-bootstrap.yml, then run workflow-bootstrap sync.\n";

function quote(value: string): string {
  return JSON.stringify(value);
}

function setupSteps(ci: CiConfig): string[] {
  switch (ci.runtime) {
    case "node": {
      const lines = [
        "      - name: Set up Node.js",
        "        uses: actions/setup-node@v6",
        "        with:",
        `          node-version: ${quote(ci.version)}`,
      ];
      if (ci.packageManager && ci.dependencyFile) {
        lines.push(`          cache: ${ci.packageManager}`);
        lines.push(`          cache-dependency-path: ${quote(ci.dependencyFile)}`);
      }
      if (ci.packageManager === "pnpm" || ci.packageManager === "yarn") {
        lines.push("      - name: Enable Corepack", "        run: corepack enable");
      }
      return lines;
    }
    case "python":
      return [
        "      - name: Set up Python",
        "        uses: actions/setup-python@v6",
        "        with:",
        `          python-version: ${quote(ci.version)}`,
        ...(ci.dependencyFile ? ["          cache: pip", `          cache-dependency-path: ${quote(ci.dependencyFile)}`] : []),
      ];
    case "go":
      return [
        "      - name: Set up Go",
        "        uses: actions/setup-go@v6",
        "        with:",
        `          go-version: ${quote(ci.version)}`,
      ];
    case "dotnet":
      return [
        "      - name: Set up .NET",
        "        uses: actions/setup-dotnet@v5",
        "        with:",
        `          dotnet-version: ${quote(ci.version)}`,
      ];
    default:
      return [];
  }
}

function qualityWorkflow(config: WorkflowConfig): string {
  const steps = ["      - uses: actions/checkout@v7", ...setupSteps(config.ci)];
  if (config.ci.install) {
    steps.push("      - name: Install dependencies", `        run: ${quote(config.ci.install)}`);
  }
  for (const command of config.ci.commands) {
    steps.push(`      - name: ${quote(command.name)}`, `        run: ${quote(command.run)}`);
  }
  if (!config.ci.install && config.ci.commands.length === 0) {
    steps.push("      - name: No project checks detected", "        run: echo 'Add CI commands to .workflow-bootstrap.yml.'");
  }

  const jobs = [
    "jobs:",
    "  checks:",
    "    runs-on: ubuntu-latest",
    "    permissions:",
    "      contents: read",
    "    steps:",
    ...steps,
  ];
  if (config.ci.helm.length > 0) {
    jobs.push(
      "",
      "  helm:",
      "    runs-on: ubuntu-latest",
      "    permissions:",
      "      contents: read",
      "    steps:",
      "      - uses: actions/checkout@v7",
      "      - name: Set up Helm",
      "        uses: azure/setup-helm@v5",
      "        with:",
        "          version: v4.2.3",
    );
    for (const helm of config.ci.helm) {
      jobs.push(
        `      - name: ${quote(`Validate ${helm.chart}`)}`,
        "        shell: bash",
        "        run: |",
        "          set -euo pipefail",
        `          helm lint ${quote(helm.chart)}`,
      );
      for (const values of helm.values) {
        jobs.push(`          helm template validation ${quote(helm.chart)} -f ${quote(values)} > /dev/null`);
      }
    }
  }
  return `${GENERATED}name: Quality checks\n\non:\n  workflow_call:\n\n${jobs.join("\n")}\n`;
}

function reusablePath(config: WorkflowConfig, workflow: string): string {
  return `${config.platformWorkflows.split("@")[0]}/.github/workflows/${workflow}@${config.platformWorkflows.split("@")[1]}`;
}

function componentsInput(config: WorkflowConfig, indent = 6): string[] {
  const spaces = " ".repeat(indent);
  return [`${spaces}components: >-`, `${spaces}  ${JSON.stringify(config.containers.components)}`];
}

function pullRequestWorkflow(config: WorkflowConfig): string {
  const lines = [
    GENERATED.trimEnd(),
    "name: Pull request",
    "",
    "on:",
    "  pull_request:",
    `    branches: [${config.project.defaultBranch}]`,
    "",
    "concurrency:",
    "  group: pr-${{ github.event.pull_request.number }}",
    "  cancel-in-progress: true",
    "",
    "jobs:",
    "  checks:",
    "    uses: ./.github/workflows/quality.yml",
    "    permissions:",
    "      contents: read",
  ];
  if (config.deployment.preview.enabled && config.containers.components.length > 0) {
    lines.push(
      "",
      "  preview-images:",
      "    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}",
      "    needs: checks",
      `    uses: ${reusablePath(config, "build-images.yml")}`,
      "    permissions:",
      "      contents: read",
      "      packages: write",
      "    with:",
      ...componentsInput(config),
      "      image-tag: pr-${{ github.event.pull_request.number }}",
      `      registry: ${config.containers.registry}`,
    );
  }
  return `${lines.join("\n")}\n`;
}

function stagingWorkflow(config: WorkflowConfig): string {
  const hasImages = config.containers.components.length > 0;
  const lines = [
    GENERATED.trimEnd(),
    "name: Staging CI/CD",
    "",
    "on:",
    "  push:",
    `    branches: [${config.project.defaultBranch}]`,
    "",
    "concurrency:",
    `  group: ${config.project.name}-staging`,
    "  cancel-in-progress: false",
    "",
    "jobs:",
    "  checks:",
    "    uses: ./.github/workflows/quality.yml",
    "    permissions:",
    "      contents: read",
  ];
  if (hasImages) {
    lines.push(
      "",
      "  build:",
      "    needs: checks",
      `    uses: ${reusablePath(config, "build-images.yml")}`,
      "    permissions:",
      "      contents: read",
      "      packages: write",
      "    with:",
      ...componentsInput(config),
      "      image-tag: main-${{ github.sha }}",
      "      moving-tag: staging",
      `      registry: ${config.containers.registry}`,
    );
  }
  if (config.deployment.staging.enabled && config.deployment.staging.updates.length > 0) {
    lines.push(
      "",
      "  promote:",
      `    needs: ${hasImages ? "build" : "checks"}`,
      `    uses: ${reusablePath(config, "promote-yaml.yml")}`,
      "    permissions:",
      "      contents: write",
      "    with:",
      "      updates: >-",
      `        ${JSON.stringify(config.deployment.staging.updates)}`,
      "      value: main-${{ github.sha }}",
      `      branch: ${config.project.defaultBranch}`,
      "      expected-sha: ${{ github.sha }}",
      "      commit-message: \"chore(staging): deploy main-${{ github.sha }} [skip ci]\"",
    );
  }
  return `${lines.join("\n")}\n`;
}

function releaseWorkflow(config: WorkflowConfig): string {
  return `${GENERATED}name: Release images

on:
  release:
    types: [published]

concurrency:
  group: release-\${{ github.event.release.tag_name }}
  cancel-in-progress: false

jobs:
  checks:
    uses: ./.github/workflows/quality.yml
    permissions:
      contents: read

  build:
    needs: checks
    uses: ${reusablePath(config, "build-images.yml")}
    permissions:
      contents: read
      packages: write
    with:
${componentsInput(config, 6).join("\n")}
      image-tag: \${{ github.event.release.tag_name }}
      moving-tag: stable
      registry: ${config.containers.registry}
      checkout-ref: \${{ github.event.release.tag_name }}
`;
}

function liveWorkflow(config: WorkflowConfig): string {
  return `${GENERATED}name: Deploy to production

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release tag to promote, for example v1.2.3
        required: true
        type: string

concurrency:
  group: ${config.project.name}-production
  cancel-in-progress: false

jobs:
  promote:
    uses: ${reusablePath(config, "promote-yaml.yml")}
    permissions:
      contents: write
    with:
      updates: >-
        ${JSON.stringify(config.deployment.production.updates)}
      value: \${{ inputs.version }}
      required-prefix: v
      value-regex: '^v[0-9]+\\.[0-9]+\\.[0-9]+(-[0-9A-Za-z.-]+)?$'
      branch: ${config.project.defaultBranch}
      commit-message: "chore(production): deploy \${{ inputs.version }} [skip ci]"
`;
}

function workflowDocumentation(config: WorkflowConfig): string {
  const components = config.containers.components.length > 0
    ? config.containers.components.map((component) => `- \`${component.name}\` builds \`${component.image}\` from \`${component.dockerfile}\`${component.target ? ` target \`${component.target}\`` : ""}.`).join("\n")
    : "- No container builds were detected.";
  return `# Delivery Workflows

This repository uses workflows generated by
\`@mythral0/workflow-bootstrap\`. The source configuration is
\`.workflow-bootstrap.yml\`.

## Flow

1. Pull requests run the detected quality and Helm checks.
2. A merge to \`${config.project.defaultBranch}\` repeats those checks against the merged commit.
3. Successful checks build the configured images.
4. Staging GitOps values are updated only after image builds pass. Staging runs are serialized.
5. Publishing a GitHub Release builds immutable release images.
6. Production promotion is a separate manual workflow that updates GitOps values.

## Components

${components}

## Maintenance

Edit \`.workflow-bootstrap.yml\`, then regenerate and validate:

\`\`\`bash
npx @mythral0/workflow-bootstrap sync
npx @mythral0/workflow-bootstrap check
\`\`\`

Generated workflows call \`${config.platformWorkflows}\`. GitOps reconciliation is
performed by the deployment controller; GitHub Actions does not connect directly
to the cluster.

The GitHub Actions token needs permission to update the deployment branch. If
branch protection requires pull requests, grant the Actions bot an explicit
bypass or replace direct promotion commits with an approved deployment pull
request policy.
`;
}

export function renderConfig(config: WorkflowConfig): string {
  return stringifyYaml(config, { lineWidth: 0 });
}

export function renderFiles(config: WorkflowConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [
    { path: ".workflow-bootstrap.yml", content: renderConfig(config) },
    { path: ".github/workflows/quality.yml", content: qualityWorkflow(config) },
    { path: ".github/workflows/pull-request.yml", content: pullRequestWorkflow(config) },
    { path: ".github/workflows/staging.yml", content: stagingWorkflow(config) },
    { path: "docs/workflows.md", content: workflowDocumentation(config) },
  ];
  if (config.containers.components.length > 0) {
    files.push({ path: ".github/workflows/release.yml", content: releaseWorkflow(config) });
  }
  if (config.deployment.production.enabled && config.deployment.production.updates.length > 0) {
    files.push({ path: ".github/workflows/deploy-production.yml", content: liveWorkflow(config) });
  }
  return files;
}
